### ISSUE TITLE
amplitude does not load

### ISSUE THREAD

**Issue by zowers** [segmentio/analytics.js-core#11]
we load scripts with `crossOrigin="anonymous"` as described in https://github.com/jrburke/requirejs/issues/687
```
    var requirejs_createNode = requirejs.createNode;
    requirejs.createNode = function createNodeAddCors( config, moduleName, url ) {
        var node = requirejs_createNode(config, moduleName, url);
        node.crossOrigin = "anonymous";
        return node;
```

But the https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.4.1-min.gz.js does not load
```
Script from origin 'https://d24n15hnbwhuhn.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://our-server.com' is therefore not allowed access.
```

Please avoid using global `window.require` or ensure the integration works with `crossOrigin="anonymous"`
crossposting from https://github.com/segmentio/analytics.js/issues/487

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!

**Comment by zowers** [comment]
oh, that's nice
the issue is still present, we have to work it around
```javascript
    var requirejs_createNode = requirejs.createNode;
    requirejs.createNode = function createNodeAddCors( config, moduleName, url ) {
        var node = requirejs_createNode(config, moduleName, url);
        if (url.indexOf("{{ scriptsRoot }}") == 0)
                node.crossOrigin = "anonymous";

        return node;
```

**Comment by hankim813** [comment]
https://github.com/segmentio/analytics.js/issues/487#issuecomment-217089509 we'll discuss here <-- since I already made the comment there >.<
