### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'analytics.load('key')

### ISSUE THREAD

**Issue by lpender** [segmentio/analytics.js-core#12]
Your [Quickstart Guide](https://segment.com/docs/libraries/analytics.js/quickstart/) states to perform the following steps to load analytics:

```
<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||...
  analytics.load("YOUR_WRITE_KEY");
  analytics.page()
  }}();
</script>
```

However, there is no documentation about how to use the `analytics.js` as, i.e. a bundled node package.

Something like the following:

```
var analytics = require('analytics.js');

analytics.load('abc');
```

Results in an error: 

```
TypeError: 'undefined' is not a function (evaluating 'analytics.load('key')
```

It's clear that this the JS contained in this repository is not the same as the minified JS in the Getting Started example.

How do you explain that?  Why doesn't the `.load` method work?

Please help!

Thanks!
-Lee

**Comment by lpender** [comment]
I've unminified and read through the JS in your quickstart guide--it looks like it loads analytics from a CDN via script injection.

**Comment by rhys-vdw** [comment]
I still don't understand how to provide the write key to this library...

**Comment by f2prateek** [comment]
The open source version of analytics.js doesn't need/use a write key. You provide settings for all the providers directly.

**Comment by raam86** [comment]
What's the best way to include the analytics.js script in a webpage?

using a `<script>` tag results in `global` not defined and using `index.js` in the source results in requite not defined?

**Comment by krtrice** [comment]
@lpender what was your resolution to the `load` method being undefined?
