### ISSUE TITLE
Support for new Facebook Pixel in analytics.js

### ISSUE THREAD

**Issue by albybarber** [segmentio/analytics.js-core#13]
Hi All,

Will you be integrating `https://github.com/segment-integrations/analytics.js-integration-facebook-pixel` into analytics.js?

Thanks.

**Comment by f2prateek** [comment]
We should. Please open this issue on the right repo - https://github.com/segmentio/analytics.js

**Comment by albybarber** [comment]
Thanks @f2prateek - I have done just that :smile_cat:  - https://github.com/segmentio/analytics.js/issues/497
