### ISSUE TITLE
Is this Library Tree-Shakable?

### ISSUE THREAD

**Issue by pxwee5** [segmentio/analytics.js-core#183]
From the docs it appears that this is a JS dependency library for 
```
https://cdn.segment.com/analytics.js/v1/analytics.min.js
```

I think we may only be using the `track`, `reset` and `identify` syntaxes and not the others. 
And from the readme it appears that we can tree-shake this so I just want to confirm this in advance.

**Comment by pooyaj** [comment]
@pxwee5 you are correct, this library is bundled into `analytics.min.js` that is served from Segment CDN. You can use this library as a standalone package if not want to use the CDN version. I haven't tried to treeshake the library, but as far as I know you won't be able to treeshake individual methods. The library exports a single `Analytics` and also doesn't use es modules.

**Comment by pxwee5** [comment]
Any plans to make this library tree shakable? Or does it make no difference since the library needs every 60KB in order to send tracking information ?
