### ISSUE TITLE
Instructions for using node module do not work

### ISSUE THREAD

**Issue by jd-lacey** [segmentio/analytics.js-core#205]
The instructions say

// instantiate the library
const analytics = new Analytics();

When I try to do this it says:
"/node_modules/@segment/analytics.js-core/build/analytics")' has no construct signatures."

**Comment by bryanmikaelian** [comment]
Thanks for the report @jd-lacey . We'll investigate and see what's up.

**Comment by bryanmikaelian** [comment]
Looks like this was introduced in v4.1.0.  We'll see what happened and get it fixed up.  In the meantime, you can pin your version to v4.0.4

**Comment by bryanmikaelian** [comment]
@jd-lacey This is resolved in v4.1.1

**Comment by jd-lacey** [comment]
Doesn't seem to be resolved for me @bryanmikaelian after upgrading to 4.1.4

**Comment by Timo614** [comment]
I'm a bit new to typescript so apologies if this is bad syntax but I was able to get around this error via:

```
import Analytics from '@segment/analytics.js-core/build/analytics';
import { SegmentAnalytics } from '@segment/analytics.js-core';
const analytics: SegmentAnalytics.AnalyticsJS = new (Analytics as any)();
```

Not sure if there are any negatives to that approach but I do see my events appear on segment's side when I track them and I'm no longer running into that error related to the construct signatures.

**Comment by Timo614** [comment]
Keep in mind if you go with this approach a few caveats I noticed:
- The typescript interfaces currently have some issues around the page forcing you to specify empty strings or undefined for optional parameters in many cases.

To get page working I had to specify an empty category name for example.
```
                   analytics.page(
                        '',
                        loc.pathname,
                        {
                            path: loc.pathname
                        },
                        {},
                        undefined
                    );
```
- All integrations must be manually handled and configured (somewhat defeating the purpose of segment.io for managing this)

IE you want amplitude:
```
import Analytics from '@segment/analytics.js-core/build/analytics';
import SegmentIntegration from '@segment/analytics.js-integration-segmentio';
import AmplitudeIntegration from '@segment/analytics.js-integration-amplitude';
import { SegmentAnalytics } from '@segment/analytics.js-core';

const analytics: SegmentAnalytics.AnalyticsJS = new (Analytics as any)();
const integrationSettings = {
    'Segment.io': {
        apiKey: "REDACTED",
        retryQueue: true,
        addBundledMetadata: true
    },
    'Amplitude': {
        apiKey: "REDACTED",
        retryQueue: true,
    }
};
analytics.use(SegmentIntegration);
analytics.use(AmplitudeIntegration);
analytics.initialize(integrationSettings);
```

I'm switching to the snippet to avoid the latter issue. Anyhow posting if it's helpful sorry if it's not / more distracting just figured I'd chip in with my experiences (I'm not very good at typescript though).

**Comment by bscaspar** [comment]
I am on @segment/analytics.js-core version 4.1.5 and also see that analytics.d.ts is simply `export {};` 

Better type support overall would be greatly appreciated!

**Comment by dmngu9** [comment]
should this be opened again? I have the same issue

**Comment by livthomas** [comment]
Over 90% of the code in this repository is written in TypeScript. And still we cannot import it properly in our TypeScript projects. Can you please make sure this library can be used without any "hacks"? Or can you write down those workarounds so people won't spend countless hours trying to do such a simple thing as adding this library to their TypeScript projects?
