### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by jd-lacey** [segmentio/analytics.js-core#209]
Using 4.1.1

Compiled with warnings.

./node_modules/@segment/analytics.js-core/build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by bryanmikaelian** [comment]
@jd-lacey Thanks for the report.  Just out of curiosity, how are you importing the library?  I am not seeing the issue in a test sandbox.  This is with both commonjs and ES6-style imports.

Here is the sandbox https://codesandbox.io/s/how-to-use-segment-as-npm-package-forked-wy95f?file=/src/index.js
