### ISSUE TITLE
No types for import SegmentIntegration from "@segment/analytics.js-integration-segmentio";

### ISSUE THREAD

**Issue by jd-lacey** [segmentio/analytics.js-core#212]
Trying to import as per the documentation doesn't work

import SegmentIntegration from '@segment/analytics.js-integration-segmentio

Could not find a declaration file for module '@segment/analytics.js-integration-segmentio'. react/node_modules/@segment/analytics.js-integration-segmentio/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/segment__analytics.js-integration-segmentio` if it exists or add a new declaration (.d.ts) file containing `declare module '@segment/analytics.js-integration-segmentio';`ts(7016)

**Comment by benjipott** [comment]
@jd-lacey add a folder @types/segment/index.d.ts on the root directory

in index.d.ts add this line of code 
declare module '@segment/analytics.js-integration-segmentio'
