### ISSUE TITLE
User overrides of 'properties' on '.page' call are not honored

### ISSUE THREAD

**Issue by fchu** [segmentio/analytics.js-core#218]
Hi there!

I think I found a bug in how the `.page` call does overrides:

# Environment 
node: 12.19.1
@segment/analytics.js-core: 4.1.5
@segment/analytics.js-integration-segmentio: 4.2.5

# Setup
Setup Similar to https://github.com/segmentio/analytics.js-core

# Observed results
When making the following call (using Vue):
```ts
    // Make a page call for each navigation event
    analytics.page(undefined, to.name || '', {
      path: to.fullPath,
      referrer: from.fullPath,
    });
```
the analytics tracked on Segment actually returns the default obtained by the `document`

# Expected Results
Page and referrer should get overridden, as specified on [the doc](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#basic-tracking-methods)

# Thoughts
I see on [this commit](https://github.com/segmentio/analytics.js-core/commit/7b59f340e212976e3ae7664d67c91404ac077323) a FIXME that might be related to this issue, though I am not 100% sure.

If anything, the old code seem to propagate user overrides correctly into the `context.page` object, while the new code doesn't because `properties` gets overridden the other way around by the statement:
```
properties = {
    ...properties,
    ...defs
  }
```
before it gets any chance to make it to `context.page`.

Thank you!

**Comment by nicest123** [comment]
We are seeing the same issue ... any help or pointers on how to override the url property in the page call.
