### ISSUE TITLE
update facade to 2.x

### ISSUE THREAD

**Issue by ndhoule** [segmentio/analytics.js-core#3]
Not sure if there's a reason why, but analytics.js tracks the `1.x` branch of facade. Makes maintenance kinda hard and also means we've missed out on a bunch of improvements (e.g. cloning/traverse spring to mind)

cc @yields @gjohnson, any missing context here I should know about?

**Comment by hankim813** [comment]
Will triage internally https://segment.atlassian.net/browse/INT-272
