### ISSUE TITLE
Setting custom `campaign` properties

### ISSUE THREAD

**Issue by SpainTrain** [segmentio/analytics.js-core#34]
Hello.  I cannot seem to get custom campaign properties sent in `context` for a `page` call.

Here is the code on the page:

```js
!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
	analytics.load("<key>");

	function getQueryVariable(variable) {
    	var query = window.location.search.substring(1);
    	var vars = query.split("&");
    	for (var i=0;i<vars.length;i++) {
        	var pair = vars[i].split("=");
        	if(pair[0] == variable){return pair[1];}
    	}
    	return(void 0);
	}

	var campaign = {
        name: getQueryVariable("ctx_campaign"),
        source: getQueryVariable("ctx_source"),
        medium: getQueryVariable("ctx_medium"),
        term: getQueryVariable("ctx_term"),
        content: getQueryVariable("ctx_content")
    }

	window.console && window.console.log && window.console.log('campaign', campaign)

	analytics.page({}, {
      	context: {campaign: campaign},
     	campaign: campaign
	});
}}();
```

The campaign object prints correctly to the console. However, the API call does not include `campaign`:

```
{
  "context": {
    "campaign": {
      
    },
    "page": {
      "path": "\/offer",
      "referrer": "",
      "search": "?ctx_source=spaintrain&ctx_term=spain,train&ctx_campaign=spainzy",
      "title": "[Pricing - Step 1] Pricing.Full.Length.1.20",
      "url": "http:\/\/pricing-analysis.myhomezen.com\/offer?ctx_source=spaintrain&ctx_term=spain,train&ctx_campaign=spainzy"
    },
    "userAgent": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/56.0.2924.87 Safari\/537.36",
    "library": {
      "name": "analytics.js",
      "version": "3.0.0"
    }
  },
  "integrations": {
    
  },
  "properties": {
    "path": "\/offer",
    "referrer": "",
    "search": "?ctx_source=spaintrain&ctx_term=spain,train&ctx_campaign=spainzy",
    "title": "[Pricing - Step 1] Pricing.Full.Length.1.20",
    "url": "http:\/\/pricing-analysis.myhomezen.com\/offer?ctx_source=spaintrain&ctx_term=spain,train&ctx_campaign=spainzy"
  },
  "category": null,
  "name": null,
  "anonymousId": "be16ec17-7f10-4f70-9072-df5491ce78ec",
  "timestamp": "2017-02-24T23:25:04.878Z",
  "type": "page",
  "writeKey": "<key>",
  "userId": "<id>",
  "sentAt": "2017-02-24T23:25:04.881Z",
  "_metadata": {
    "bundled": [
      "AdRoll",
      "Amplitude",
      "Facebook Pixel",
      "Google Analytics",
      "Google Tag Manager",
      "Lucky Orange",
      "Mixpanel",
      "Segment.io"
    ],
    "unbundled": [
      
    ]
  },
  "messageId": "ajs-55423f6e71370b8998553bd7d25c2009"
}
```

It is possible to see this live at https://pricing-analysis.myhomezen.com/offer?ctx_source=spaintrain&ctx_term=spain,train&ctx_campaign=spainzy

It seems to be supported, because I updated the page event test like so and it still passes:

```js
    it('should accept top level option .context', function() {
      var app = { name: 'segment' };
      var campaign = { name: 'segment' };
      analytics.page({ prop: true }, { context: { app: app, campaign: campaign } });
      var page = analytics._invoke.args[0][1];
      assert.deepEqual(app, page.obj.context.app);
      assert.deepEqual(campaign, page.obj.context.campaign);
    });
```

Is this intended to be supported?  If so, pointers on where to look next to find the issue?

**Comment by brennan** [comment]
Here there, @SpainTrain - I just responded to your ticket in ZenDesk. Segment's Analytics.js library parses UTM parameters automatically for you. I've sent along some examples of it in action and working as expected on your homepage.

**Comment by SpainTrain** [comment]
Thanks! I am familiar with that feature, but using those querystrings conflicts with GA auto-tagging - 

https://support.google.com/analytics/answer/1033981?hl=en
https://support.google.com/analytics/answer/1733663

We need to be able to set the campaign properties without negative repercussions in our google analytics data.

Regarding this GH issue specifically, I think the question I posed still is valid regarding the library


> Is this intended to be supported?

Is it in the intention to support this functionality?  If not, what is the rationale for not allowing it?

Thanks again!

**Comment by f2prateek** [comment]
Just so I understand, you're expecting a random query parameter (in this case `ctx_campaign` and friends)  to automatically be pulled in by analytics.js? 

We can't do this by default, because you don't control these query parameters, and arbitrarily collecting all would bloat your data. We already made this mistake by not making our UTM parser strict https://github.com/segment-integrations/analytics.js-integration-segmentio/pull/3/files.

The best way to support this would be via default context object. This way you can set your custom context fields once, and all events will pick it up.
https://github.com/segmentio/analytics.js-core/issues/26

For now, you'll have to send context manually for your tracking calls.

**Comment by SpainTrain** [comment]
> you're expecting a random query parameter ...  to automatically be pulled in by analytics.js?

No.  See the example above, in particular:

```js
analytics.page({}, {
      	context: {campaign: campaign},
     	campaign: campaign
	});
```

The code extracts the custom qs params and calls `page` with them in context.  However, that additional context does not show up in the resulting XHR (as also pasted above).

The updated test case pasted above simplifies this to a minimal example.  So that it's completely clear, I opened a PR with that change to the test - https://github.com/segmentio/analytics.js-core/pull/35/files

I saw #26 before opening this this, issue.  While it would indeed collaterally solve this issue (and would be great if #30 is merged),  it is a new feature whereas it is still unclear whether `context.campaign` being stripped from `page` calls is a bug.

> For now, you'll have to send context manually for your tracking calls.

As a temp workaround I can try this and see how it looks in our analytics services.  However, there currently are no `track` calls on our landing page (see above), so we will need to contrive one to populate the campaign info.  I am still unclear on why `context.campaign` is supported in `track` calls, but not `page` calls?  Is this intended behavior?

Thanks again!

**Comment by f2prateek** [comment]
Got it - thanks for the example. That cleared things up.

This looks like a bug in the segment integration https://github.com/segment-integrations/analytics.js-integration-segmentio/blob/master/lib/index.js#L216. It should be checking for an existing `campaign` object, and override it only if one is provided. The code should be something like this:

```js
if (query && !ctx.campaign) ctx.campaign = utm(query);
```

**Comment by f2prateek** [comment]
Until the fix is made in the Segment integration, merging #30 to send default context for this purpose (campaign context) won't work either.

**Comment by SpainTrain** [comment]
I had not looked into that repo, thanks for pointing that out.

Looks like you already saw it, but I opened https://github.com/segment-integrations/analytics.js-integration-segmentio/pull/26 with your fix and tests.

Thanks!

**Comment by zsherman** [comment]
Not sure if something changed but this still doesn't work for me using the latest analytics.js
