### ISSUE TITLE
Avoid exposing the full package.json in the build

### ISSUE THREAD

**Issue by francois2metz** [segmentio/analytics.js-core#37]
Hi,

While building my own version of analytics.js, I found that the full content of package.json from this package is exposed into the resulting build. 
The faulty line is https://github.com/segmentio/analytics.js-core/blob/3b48c44a3d6537a9e695810292101be8c2bb2dee/lib/index.js#L19

I would suggest to use [package-json-versionify](https://github.com/nolanlawson/package-json-versionify), either by adding the transform in the package.json or by updating analytics.js and using a global transform.

Note: the content is also exposed in the segment's build.

**Comment by f2prateek** [comment]
Tracking in https://segment.atlassian.net/browse/LIB-146

**Comment by amfred** [comment]
This one has been around for a long time, so I'd like to upvote/bump it.

**Comment by e1himself** [comment]
https://www.npmjs.com/package/packageify

**Comment by e1himself** [comment]
@danieljackins yes, this is still a problem.

`package.json` contents is still included into every segment-generated analytics build.

This increases traffic for you and for our users. For no real reason.

![Знімок з 2020-03-06 13-59-11](https://user-images.githubusercontent.com/370680/76081851-b1cc6000-5fb2-11ea-9ae9-5b36981cfe40.png)

**Comment by danieljackins** [comment]
@e1himself thanks for the ping, I'll make sure I look into getting this fix prioritized as soon as possible.

**Comment by danieljackins** [comment]
This issue has been resolved and is currently being rolled out to Segment customers
