### ISSUE TITLE
analytics.identify and analytics.page options arguments interfere with eachother

### ISSUE THREAD

**Issue by ryan-schroeder** [segmentio/analytics.js-core#39]
I'm testing this with Intercom, and getting really weird behavior: for example, this options array:

options = { integrations: { 'All': false } }
analytics.identify( 123, { ... }, options )
analytics.page()

causes intercom JS to still run on the page, and a javascript error appears (invalid user_hash for intercom, because I am not sending intercom the sign-in data it wants.  But it should not be running at all).

If I do this, however, no intercom JS runs on the page, and no error appears:

options = { integrations: { 'All': false } }
analytics.identify( 123, { ... }, options )
analytics.page(null, null, null, options)

Notice that I am sending "options" to both identify and page

If I only send the "options" object to page but not to identify, I'm back to the same javascript error message.  This seems goofy and isn't documented; can you add a note about this to the docs here https://segment.com/docs/sources/website/analytics.js/#selecting-integrations ?

**Comment by f2prateek** [comment]
Options doesn't define whether a tool is running or not. That is controlled based on the initialization settings (if you're using the segment hosted version the initialization settings are controlled from your Segment dashboard).

Options simply says, don't send a particular *single* message to a tool, it does not apply to *all* messages.

So `analytics.identify( 123, { ... }, { integrations: { 'All': false } })` won't send the identify call to Intercom. But `analytics.page()` will still send it to intercom. You need to send `{ integrations: { 'All': false } }` as the options for *every* call you don't want to send to intercom (the default behaviour is to send every call to all enabled integrations).

**Comment by f2prateek** [comment]
I updated the document to clarify the options object does not apply globally.

**Comment by ryan-schroeder** [comment]
Thanks for the explanation and for updating the docs!  This isn't a help forum so no need to reply, but I'm still a little confused about:

"Options doesn't define whether a tool is running or not. That is controlled based on the initialization settings (if you're using the segment hosted version the initialization settings are controlled from your Segment dashboard)."

I need to selectively disable tools progamatically (on certain pages or for certain users, for example).  I don't think I can do that from the segment dashboard?

But this solution works for me (sending the options along with every request does stop the intercom tool from being loaded on the web page) so I'm happy with that, thanks again!

**Comment by f2prateek** [comment]
> I need to selectively disable tools progamatically (on certain pages or for certain users, for example). I don't think I can do that from the segment dashboard?

That's correct, and is the root of the problem here. This is not possible at the moment using the Segment hosted version since the settings for analytics.js are defined per project/writeKey, rather than per page.

The only real way to do this would be to use a different segment project per page or set of pages (e.g. at Segment we use a different project/writeKey for our public site and for users logged in to the app).
