### ISSUE TITLE
Protocol and domain are missed with canonical url

### ISSUE THREAD

**Issue by abiaskosty** [segmentio/analytics.js-core#40]
If canonical URL is present it's value is used as `context.page.url` value. 
Unlike `window.location.href` or `href` attribute of `<a>` tag, canonical tag doesn't convert absolute or relative path to fully qualified url. 
For example for `<link rel="canonical" href="/absolute/path" />` returned value will be `"/absolute/path"`.
In such case, it's not possible to guess protocol and domain from an event data.

**Comment by f2prateek** [comment]
Sorry for the delay. I think I'd prefer to leave the canonical URL untouched here - that could cause more confusion down the line.

One thing we're considering here is to skip using the canonical URL by default and giving folks the option to use `window.location.href` instead.
