### ISSUE TITLE
Cannot use with webpack

### ISSUE THREAD

**Issue by paulsouche** [segmentio/analytics.js-core#55]
Hi,

```typescript
import * as analytics from '@segment/analytics.js-core';
```

Fails with webpack. Warning

```bash
WARNING in /node_modules/@segment/analytics.js-core/lib/index.js
15:20-27 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Because of [this line](https://github.com/segmentio/analytics.js-core/blob/master/lib/index.js#L16) transpiled into

```javascript
analytics.require = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```

Everything works fine without it. If this is deprecated could you please remove it ? Do you need a PR for it ?

Will have a look at `ContextReplacementPlugin` because seems related to https://github.com/webpack/webpack/issues/2670 and https://github.com/webpack/webpack/issues/2675

**Comment by alexlevy0** [comment]
+1 Same issue here

**Comment by f2prateek** [comment]
Docs on using analytics.js can be found here https://segment.com/docs/sources/website/analytics.js/. Webpack is not currently supported.

**Comment by danieljackins** [comment]
Closing this issue. If this is still a problem, please reopen so that we can get it properly reprioritized.
