### ISSUE TITLE
node-uuid V2 is deprecated

### ISSUE THREAD

**Issue by paulsouche** [segmentio/analytics.js-core#58]
node-uuid v2 is deprecated. As it is used only to generate anonymousId v4, it should be updated to uuid v3.

Thanks

**Comment by f2prateek** [comment]
Thanks for letting us know!  I've triaged this internally https://segment.atlassian.net/browse/LIB-235. I don't have an ETA, but we'll post updates here.

**Comment by danieljackins** [comment]
we're on uuid v3 now, closing this
