### ISSUE TITLE
Using link(rel="canonical") is not SPA friendly

### ISSUE THREAD

**Issue by cristiandouce** [segmentio/analytics.js-core#8]
This part of the code affects many SPAs defaults: https://github.com/segmentio/analytics.js-core/blob/b0f193f897df610a5d2c3fe5fda3af44a0e4479c/lib/pageDefaults.js#L20

Asuming HTML structure is `correct` is an old fail from many browsers IMHO. jQuery understood it perfectly on it's Sizzle engine that ids are still going to be duplicated in the same DOM context.

Anyway, the thing is that if in the first load of the page, your server framework delivers a canonical path in a `link(rel="canonical")`, and your SPA framework does not handle it on each `push state change`, the reported `path` and `url` properties is always the one from the first load, and not the actual page as it should.

I'm not sure if this was an intended behavior neither it's reasons. I just think there should be a way to turn this off at least.

Thanks!

**Comment by sperand-io** [comment]
@cristiandouce agreed — this should absolutely be optional at worst and (imo) would be removed at best. we're evaluating the best course of action.

In the meantime, in the `page()` call that you trigger on `push state change`, if you pass the url explicitly to the call, that will take precedence over the canonical default: https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L431

something like: 

```
routeChange.handlerFunc(function() {
  analytics.page({ url: document.location.href });
 })
```

thanks for the feedback! leaving open until we decide what do to hear and make an improvement.

**Comment by cristiandouce** [comment]
I didn't find that usage in the [Documentation page](https://segment.com/docs/libraries/analytics.js/#page). Neither an full API Doc here at this repository. It'd have saved me a lot of time, haha.

Also we ended up updating the canonical link (or removing it when not needed). Not the best, but it worked.

Is there anywhere public to submit pull requests to Segment's documentation? I'd gladly submit some stuff from time to time :smile: Maybe some specific usage examples for SPAs vs Server based applications.

Thanks!

**Comment by sperand-io** [comment]
@cristiandouce great point! I will add that to the docs tomorrow. so sorry you had to delve into the code to find out what was going on there, totally unacceptable. 

As for a public repo for our docs, first of all, thanks so much for your willingness to contribute! You have no idea how happy that makes me to hear. We've debated opening them up for contribution several times, I'll take your comment as ammunition to a rekindled discussion on that front! Hopefully we can do that soon!

**Comment by cristiandouce** [comment]
@hankim813 hey, has this been made optional? I now see you mention how it works in the docs, but I don't see how to disable that first lookup if I want to.

**Comment by hankim813** [comment]
@cristiandouce it is not yet supported but we've triaged it internally so that we can ship that feature hopefully soon!
